### ISSUE TITLE
Wrong name or missing Countries

### ISSUE THREAD

**Issue by VisiGod** [dr5hn/countries-states-cities-database#227] opened 2021-06-06 18:13 UTC
First let me thank you for all the work you've put into this and take this issue as an improvement

"Croatia (Hrvatska)" - Should be named only "Croatia"
"Netherlands The" - Should be named "Netherlands" or "The Netherlands"
"Korea North" - Should be named North Korea
"Korea South" - Should be named South Korea
"England", "Northern Ireland", "Scotland", "Wales" don't exist (they are countries inside the United Kingdom but are recognized as countries)

**Comment by dr5hn** [comment] 2021-06-07 06:35
@VisiGod You're most welcome.

The first 4 points are clear, the last one is doubtful. I will take a look at it soon and let you know if any questions.

**Comment by VisiGod** [comment] 2021-06-13 11:05
Regarding the last issue, sometimes we need to select a specific country inside UK and since they aren't available, it's a deal breaker for some uses.

**Comment by dr5hn** [comment] 2021-06-13 11:20
@VisiGod Currently `"England", "Northern Ireland", "Scotland", "Wales"` These are marked as a States. So you mean we need to mark them as a country instead of States?

**Comment by VisiGod** [comment] 2021-07-04 21:05
@dr5hn I think they should be marked as countries and not states. California is a US state as West Midlands is a region of England.

All four are countries in my understanding:
England - https://en.wikipedia.org/wiki/England
Northern Ireland - https://en.wikipedia.org/wiki/Northern_Ireland
Scotland - https://en.wikipedia.org/wiki/Scotland
Wales - https://en.wikipedia.org/wiki/Wales

Or you may check https://en.wikipedia.org/wiki/Countries_of_the_United_Kingdom

Although some people refer to the UK as a country (not wrong), their constituent are also countries.

**Comment by joaorb64** [comment] 2021-07-24 15:09
The first 4 I think would be very helpful changes. In all data I work on using this repo's data, these come up as special cases because of how their names are configured; while the data on the other side is always configured with the suggested names.

**Comment by dr5hn** [comment] 2021-07-25 15:56
@VisiGod //cc @joaorb64 I've fixed the first 4 naming issues.

The Remaining needs more brainstorming. Will tackle them later.

**Comment by dr5hn** [comment] 2024-09-05 07:12
Duplicate of #290

**Closed by dr5hn** 2024-09-05 07:12 UTC
Labels: UK
