### ISSUE TITLE
No UK city

### ISSUE THREAD

**Issue by Salamouna** [dr5hn/countries-states-cities-database#680] opened 2023-09-06 10:10 UTC
I can't see any city in the UK
only states

**Comment by RezaNorm** [comment] 2023-10-28 08:02
yeah i'm facing issues with this one

**Comment by Malin88** [comment] 2023-11-09 11:35
same here :/

**Comment by ClearSeve** [comment] 2023-12-13 01:06
GBR is the abbreviation of Great Britain, the UK. The more formal GBR is rarely used in UK.

**Comment by coxy17** [comment] 2024-06-09 17:19
me too

**Comment by dr5hn** [comment] 2024-09-05 07:07
Duplicate of #168

**Closed by dr5hn** 2024-09-05 07:07 UTC
