### ISSUE TITLE
Spanish cities missing lat/long

### ISSUE THREAD

**Issue by scottgigante** [dr5hn/countries-states-cities-database#767] opened 2024-03-15 16:48 UTC
City ids 151031 to 153201 are missing latitude and longitude (currently all set to 0).

**Comment by Bankole2000** [comment] 2024-07-06 02:35
This is a really serious issue... about 2171 incorrect records with the most crucial data missing... kind of ruins the data set in a lot of ways. Things like Haversine's formula or any kind of geolocation computation result can't be trusted now 😓

**Comment by dr5hn** [comment] 2024-09-05 07:13
Duplicate of #583

**Closed by dr5hn** 2024-09-05 07:13 UTC
Labels: bug, missing-records
