### ISSUE TITLE
UK states and no cities

### ISSUE THREAD

**Issue by coxy17** [dr5hn/countries-states-cities-database#784] opened 2024-06-09 17:29 UTC
Hi

I am using the demo https://dr5hn.github.io/countries-states-cities-database/ and search for e.g.  United Kingdom > Nottinghamshire and there are no cities displayed?

![Capture](https://github.com/dr5hn/countries-states-cities-database/assets/746291/eea99efd-bbe7-4219-8be7-b731eb187a1b)

Any ideas why its not working?

thanks

Nick

**Comment by coxy17** [comment] 2024-06-09 19:25
Hi
Ok thanks I will check out the API too just incase. I also checked the Demo again and found that the cities do display when selecting 'England' as a state. Why is 'England' a state? is there an error with the demo?

![Capture](https://github.com/dr5hn/countries-states-cities-database/assets/746291/bc3ee98f-bb1f-49d0-b2b7-78f3e304bee4)

**Comment by coxy17** [comment] 2024-06-09 20:52
Ok so where is the data being pulled from to use in this library? 

'England' and 'Nottinghamshire' cannot be both under the same state as 'Nottinghamshire' is a county. So i can see why it does not fit into the model as there needs to be another level. The same issue for 'Towns' appearing alongside 'Cities' e.g. 'Hucknall'. So the lists are not working for the UK. Its missing the breakdown e.g.

an overall example of a UK town is:
United Kingdom > England > Nottinghamshire > Nottingham > Hucknall

I am assuming that I cant use this library to break down like the example above.

**Comment by dr5hn** [comment] 2024-09-05 07:10
Duplicate of #1168

**Closed by dr5hn** 2024-09-05 07:10 UTC
Labels: question
